/****** Script for SelectTopNRows command from SSMS  ******/
SELECT TOP (1000) [BookID]
      ,[Title]
      ,[YearPublished]
      ,[ISBN]
      ,[PubID]
      ,[PrePageCount]
      ,[PageCount]
      ,[PostPageCount]
      ,[BindingType]
      ,[IsDiskAvialable]
      ,[PurchaseDate]
      ,[PurchaseSource]
      ,[KeyWords]
      ,[Description]
      ,[Price]
      ,[NotForIssue]
      ,[CurrentStatus]
      ,[Faults]
      ,[UserID]
      ,[EntryDate]
  FROM [OnlineLib].[dbo].[b]