/****** Script for SelectTopNRows command from SSMS  ******/
SELECT TOP (1000) [PubID]
      ,[Name]
      ,[Company_Name]
      ,[Address]
      ,[City]
      ,[State]
      ,[Pin]
      ,[Telephone]
      ,[Fax]
      ,[EmailID]
      ,[WebSite]
      ,[Comments]
  FROM [OnlineLib].[dbo].[publishers]